### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by ex0ns** [apollographql/persistgraphql#8]
Hello,

I installed this package today, but when I tried to run it, I got the following error:

```Error: Cannot find module '../lib/src/index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ex0ns/.nvm/versions/node/v7.5.0/lib/node_modules/persistgraphql/bin/persistgraphql:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Indeed, `lib/src/index.js` is missing, it seems that it should be `binary.js`, could you please take a look.

ex0ns

**Comment by Poincare** [comment]
I pushed an update last night that fixed this. What version does your error pertain to?

**Comment by ex0ns** [comment]
I tried with version persistgraphql@0.2.9 from NPM and by building commit 42ca095ff79cbadf1819f99a61ca76056fd388d6 from this repo, same issue each time

**Comment by Poincare** [comment]
Ah - I understand the issue. I just released 0.2.10 which should fix it by changing the binary import. Could you check if that works for you?

**Comment by ex0ns** [comment]
0.2.10 fixes the issue ! Thanks.

**Comment by Poincare** [comment]
Great :)
